config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'

  resources :homes
  resources :users
  resources :user_services
  resources :user_sessions
  resources :services

  get 'logout', to: "user_sessions#destroy"

  post 'us', to:"services#tudo"
  post 'seta_user_service' ,to:"services#seta_user_service"

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/recomendacao.rb
class Recomendacao < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/type_notification.rb
class TypeNotification < ActiveRecord::Base
end

app/models/type_service.rb
class TypeService < ActiveRecord::Base
  has_many :user_services

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_services
	has_many :services
	has_many :comentarios
	has_many :notifications

	validates_presence_of :email,:nome,:encrypted_password


	def self.authenticate(email,password)
		user=User.where(["email=:email",{email:email}]).first
		return user

	end

end

app/models/user_service.rb
class UserService < ActiveRecord::Base
  belongs_to :user
  belongs_to :type_service

  validates_presence_of :descricao,:type_service_id

end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model

  attr_accessor :email, :password

  def initialize(session,attribures={})

    @session=session
    @email=attribures[:email]
    @encrypted_password=attribures[:encrypted_password]
  end

  def authenticate!
    user=User.authenticate(@email,@encrypted_password)
    if user.present?
      store(user)
    else
      errors.add(:base, "Senha ou usuário invalid")

      false
    end

  end

  def store(user)
    if user.present?
      @session[:user_id]=user.id
    end
  end


  def current_user
    if @session[:user_id]==nil
      return nil
    else
      return User.find_by_id(@session[:user_id])
    end

  end

  def user_signed_in?
    @session[:user_id].present?

  end

  def destroy
    @session[:user_id]=nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  delegate :current_user, :user_signed_in?, to: :user_session

  helper_method :current_user, :user_signed_in?

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    unless user_signed_in?
      redirect_to homes_path, alert: t('VC precisa estar logado')
    end

  end

  def require_no_authentication
    if user_signed_in?
      redirect_to user_path(current_user),notice: t('Vc já estar logado')

    end
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


	before_action :require_no_authentication, only: [:index,:new,:create]
	before_action :require_authentication,only: :destroy


	def index
		@user_session=UserSession.new(session)
		@user=User.new
	end

	def show
		@@user=User.find(params[:id])
	end


	def new
		@user=User.new
	end


	def create
		@user = User.new(user_params)
		if @user.save

			@user_session=UserSession.new(session,params[:user])

			if @user_session.authenticate!

				redirect_to user_path(@user), :notice => 'Cadastro realizado com sucesso papai'
			else
				render :new ,:notice => 'algo deu errado'
			end

		end
	end

	private

	def user_params
		params.
				require(:user).permit( :email,:nome,:encrypted_password)

	end



end

app/controllers/services_controller.rb
class ServicesController < ApplicationController


  @user_service


  def seta_user_service

    @user_service=UserService.find_by_id(params[:id])

    redirect_to new_service_path

  end

  def index

    @user_services=UserService.all
    @user_service=current_user.user_services.build()

  end

  def show


    
  end

  def new
    @service=current_user.services.build
    
  end

  def create
    
  end

  def tudo

    @user_service=current_user.user_services.build(user_service_params)
    if @user_service.save
      redirect_to user_services_path, :notice => 'Cadastro de servico realizado com sucessp'
    else
      render :index
    end

  end

  def edit
    
  end

  def update
    
  end

  def destroy

  end

  private
  def user_service_params
    params.
        require(:user_service).permit(:descricao,:type_service_id)

  end
end

app/controllers/type_services_controlles.rb
class TypeServicesController < ApplicationController


  def index
    
  end

  def new
    
  end
  
  def create
    
  end

  def edit
    
  end

  def destroy

  end


  def salva 
    
  end
  
  
end

app/controllers/user_services_controller.rb
class UserServicesController < ApplicationController


  before_action :require_authentication,only:[:new,:create]

  def index

    @user_services=current_user.user_services.all

  end

  def new
    @user_service=current_user.user_services.build
  end

  def show
    @user_services=UserService.all
  end

  def create
    @user_service=current_user.user_services.build(user_service_params)
    if @user_service.save
      redirect_to user_services_path, :notice => 'Cadastro de servico realizado com sucessp'
    else
      render services_path, notice: ('Campos vazios')
    end

  end

  def edit

  end

  def destroy

  end


  def salva

  end

private
  def user_service_params
    params.
        require(:user_service).permit(:descricao,:type_service_id)

  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  before_action :require_no_authentication, only: [:new,:create]
  before_action :require_authentication,only: :destroy

  def new

    @user_session=UserSession.new(session)

  end

  def create

    @user_session=UserSession.new(session,params[:user_session])

    if @user_session.authenticate!
      redirect_to root_path, notice: ('Login realizado com sucesso')

    else
      render :new
    end

  end

  def edit
    destroy
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t("Logout realizado com sucesso")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :can_change, only: [:edit,:update,:show]



  def new
    @user = User.new

  end

  def show
    @user=User.find(params[:id])


  end

  def edit
    @user=User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save

      @user_session=UserSession.new(session,params[:user])

      if @user_session.authenticate!
        redirect_to home_path(@user), :notice => 'Cadastro realizado com sucessoqqqqq'

      end
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: ('Login realizado com sucesso')
    else
      render action: :edit
    end
  end


  private

  def user_params
    params.
        require(:user).permit(:email,:encrypted_password)

  end


  def can_change
    unless user_signed_in? && current_user==user
      redirect_to user_path(session[:user_id]),notice: t("Ação não permitida")

    end

  end


  def user
    @user ||=User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.haml
%section.principal
  .item
    %br.xs-30.sm-60
      .container
        .row
          .col-md-6.masthead-text.animated.fadeInLeftBig
            %h2.masthead-title.label-titulo Diarista Social
            %h4.label-desc
              Uma rede social que vem para facilitar contratação de serviços domésticos, disponibilizando vários tipos de serviços e ainda uma maior interatividade com quem disponibiza o mesmo.
            %br
              .masthead-actions
                %a.btn.btn-transparent.btn-jumbo.btn-intro{:href => "./page-tour.html"}
                  Saiba Mais
              / /.masthead-actions
          / /.masthead-text
          %br.xs-30.md-0
            .col-md-6.masthead-img.animated.fadeInRightBig
              .form.masthead-form.well
                %h3.text-center.label-form Cadastre-se
                %p.text-center.label-form-2 Facilite sua vida, é grátis.
                %br
                = simple_form_for @user, as: :user, url: homes_path(@user), method: :post, :html =>{:class => 'form-group'}  do |f|
                  .form-group
                    / <label class="" for="full_name">Full Name</label>
                    = f.input :nome, :autofocus => true, :label => false, :input_html => {:class => 'form-control'},:id => 'full_name', :placeholder => "Nome"
                    /%input#full_name.form-control{:placeholder => "Seu nome", :type => "text"}
                  / /.form-group
                  .form-group
                    / <label class="" for="email_address">Email Address</label>
                    = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'},:id => 'email_address', :placeholder => "Email"
                  / /.form-group
                  .form-group
                    / <label class="" for="organization">Organization</label>
                    = f.input :encrypted_password, :autofocus => true, :label => false, :input_html => {:class => 'form-control'},:id => 'senha', :placeholder => "Senha"
                    /%input#organization.form-control{:placeholder => "Sua senha", :type => "text"}
                  / /.form-group
                  .form-group
                    %button.btn.btn-secondary.btn-jumbo.btn-block{:type => "submit"} Cadastrar agora!
                  / /.form-group
              %br.xs-80
            / /.masthead-img
        / /.row
      / /.container
  / /.item


  

app/views/homes/new.html.haml
%header.header.principal
  .container
    .row
      .col-md-6.col-md-offset-1
        .content
          .pull-middle

            %p#notice
              = notice
            %h1.page-header Diarista Social
            %p.lead Rede social que auxilia na contratação de serviços domésticos.
            %button.btn.btn-primary.btn-get{:type => "button"} Comece Agora !
        .col-md-12.services
          .content
            .pull-middle
              %h1.page-header Serviços
              %p.lead Rede social que auxilia na contratação de serviços domésticos.
              %button.btn.btn-primary.btn-get{:type => "button"} Comece Agora !
      .section
        .row
          %form.form-signin.mg-btm

            %h3.heading-desc
              Cadastre-se
            .main

              tudo
        / .container
        /   .row

app/views/homes/show.html.haml
%h2
  Perfil #{current_user.email}

app/views/layouts/_footer.html.haml
/ Rodape
%section.col-md-12.rodape
  %center
    %h1 Copyright 2015 - Diarista Social- Todos os direitos reservados

app/views/layouts/_header.html.haml
%head
  %meta{:charset => "utf-8"}
  %title Diarista Social - Sua plataforma para facilitar sua vida doméstica
  %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  / %meta{:content => "JTXi7d7bKmgghlk0MjzMCxE15K_PgbbZ5eTc5t8ImQg", :name => "google-site-verification"}
  /%meta{:content => "Jogos educativos para crianças. PonksToy a marca oficial dos pais heróis", :name=> "description"}
  /%meta{:content =>"jogos educativos, pais, jogos de tabuleiro, filhos, papertoys, heróis, sócio-educativos, famílias, crianças, ponks", :name=> "keywords"}
  /%meta{:content => "http://www.ponkstoy.com/", :name => "url"}
  /%meta{:content => "Ponkstoy - Jogos educativos que aproximam você do seu filho", :property => "og:title"}
  /%meta{:content => "Jogos educativos para crianças. PonksToy a marca oficial dos pais heróis", :property => "og:description"}  
  %meta{:content => "website", :property => "og:type"}
  %meta{:content => "", :name => "author"} 
  %meta{:content => " Diarista Social - Sua plataforma para facilitar sua vida doméstica", :property => "og:title"}
  
  /%link{:href => asset_path("favicon-ponks-toy.ico"), :rel => "icon" , :alt => "favicon-ponkstoy"}
  
  = csrf_meta_tags
    
  / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
  /[if lt IE 9]
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    / Custom styles for this template

app/views/layouts/_menu.html.haml
%ul.nav.navbar-nav.navbar-right
  %li
    #signin.navbar-form{:role => "form"}
      = simple_form_for @user_session, as: :user_session, url: user_sessions_path(@user_session), method: :post, :html => {:class => "form-signin"}  do |f|
        .input-group
          %label{:for => "email"} Email:
          = f.input :email,:placeholder => "email",:autofocus => true, :label => false, :input_html => {:class => 'form-control'}
        .input-group
          %label{:for => "senha"} Senha:
          = f.input :password,:placeholder => "Password", :autofocus => true, :label => false, :input_html => {:class => 'form-control'}
        = submit_tag 'Entrar', :class => 'btn btn-primary btn-login'

app/views/layouts/_menu_logado.html.haml
%ul.nav.navbar-nav.navbar-left.nav-tre
  %li.dropdown.navbar-notification
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "./page-notifications.html"}
      %i.fa.fa-bell.navbar-notification-icon
      %span.visible-xs-inline &nbsp;Notifications
      /%b.badge.badge-primary 3
    .dropdown-menu
      .dropdown-header &nbsp;Notifications
      .notification-list
        %a.notification{:href => "./page-notifications.html"}
          %span.notification-icon
            %i.fa.fa-cloud-upload.text-primary
          %span.notification-title Notification Title
          %span.notification-description Praesent dictum nisl non est sagittis luctus.
          %span.notification-time 20 minutes ago
        / / .notification
      %a.notification-link{:href => "./page-notifications.html"} View All Notifications
    / / .dropdown-menu
  %li.dropdown.navbar-notification
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "./page-notifications.html"}
      %i.fa.fa-envelope.navbar-notification-icon
      %span.visible-xs-inline &nbsp;Messages
    .dropdown-menu
      .dropdown-header Messages
      .notification-list
        %a.notification{:href => "./page-notifications.html"}
          .notification-icon
            %img{:alt => "", :src => "../../global/img/avatars/avatar-3-md.jpg"}/
          .notification-title New Message
          .notification-description Praesent dictum nisl non est sagittis luctus.
          .notification-time 20 minutes ago
        / / .notification
      %a.notification-link{:href => "./page-notifications.html"} View All Messages
    / / .dropdown-menu
  %li.dropdown.navbar-notification.empty
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "./page-notifications.html"}
      %i.fa.fa-warning.navbar-notification-icon
      %span.visible-xs-inline &nbsp;&nbsp;Alerts
    .dropdown-menu
      .dropdown-header Alerts
      .notification-list
        %h4.notification-empty-title No alerts here.
        %p.notification-empty-text Check out what other makers are doing on Explore!
      / / .notification-list
      %a.notification-link{:href => "./page-notifications.html"} View All Alerts
    / / .dropdown-menu
%ul.nav.navbar-nav.navbar-right.nav-log
  %li
    = link_to 'Serviços' , services_path, :class => 'label-menu-logado'
  %li
    %a.label-menu-logado{:href => "javascript:;"} Solicitações
  %li.dropdown.navbar-profile
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:;"}
      %img.navbar-profile-avatar{:alt => "", :src => "../../global/img/avatars/avatar-4-sm.jpg"}
        %span.visible-xs-inline @peterlandt &nbsp;
        %i.fa.fa-caret-down
    %ul.dropdown-menu{:role => "menu"}
      %li
        %a{:href => "./page-profile.html"}
          %i.fa.fa-user
          \&nbsp;&nbsp;My Profile
      %li
        %a{:href => "./page-pricing-plans.html"}
          %i.fa.fa-dollar
          \&nbsp;&nbsp;Plans & Billing
      %li
        %a{:href => "./page-settings.html"}
          %i.fa.fa-cogs
          \&nbsp;&nbsp;Settings
      %li.divider
      %li
        %a{:href => "./account-login.html"}
          %i.fa.fa-sign-out
            = link_to t('Sair') , logout_path
          /\&nbsp;&nbsp;Logout
/ /.container

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/header'
  %body 
    %nav.navbar-default{role: 'navigation'}  
      .navbar-header
        %button.navbar-toggle.collapsed{ type:'button', data:{toggle: 'collapse', target: '#navbar'}, aria:{ expanded: 'false', controls: 'navbar'}}
          %span.sr-only Toggle navigation
          %span.icon-bar  
          %span.icon-bar
          %span.icon-bar    
        = link_to root_path, class: 'navbar-brand-no' do	
          %a.label-logo{:href => '#'} Diarista Social 

      #navbar.navbar-collapse.collapse.menu
        - unless user_signed_in?
          =render 'layouts/menu'
        -else
          =render 'layouts/menu_logado'
    = yield

    /= render 'layouts/footer'
    = stylesheet_link_tag  'application', media: 'all'
    = javascript_include_tag 'application'

app/views/layouts/menu/_menu_logado.html.haml
.container
  .row
    %h2 Multi level dropdown menu in Bootstrap 3
    %hr/
    .dropdown
      %a#dLabel.btn.btn-primary{"data-target" => "#", "data-toggle" => "dropdown", :href => "/page.html", :role => "button"}
        Dropdown
        %span.caret
      %ul.dropdown-menu.multi-level{"aria-labelledby" => "dropdownMenu", :role => "menu"}
        %li
          %a{:href => "#"} Some actionS
        %li
          %a{:href => "#"} Some other action
        %li.divider
        %li.dropdown-submenu
          %a{:href => "#", :tabindex => "-1"} Hover me for more options
          %ul.dropdown-menu
            %li
              %a{:href => "#", :tabindex => "-1"} Second level
            %li.dropdown-submenu
              %a{:href => "#"} Even More..
              %ul.dropdown-menu
                %li
                  %a{:href => "#"} 3rd level
                %li
                  %a{:href => "#"} 3rd level
            %li
              %a{:href => "#"} Second level
            %li
              %a{:href => "#"} Second level



:javascript
      $(document).ready(function(){
        $('.dropdown').hover(
          function() {
            $('.dropdown-menu', this).not('.in.dropdown-menu').stop( true, true ).slideDown('fast');
            $(this).toggleClass('open');
          },
          function() {
            $('.dropdown-menu', this).not('.in.dropdown-menu').stop( true, true ).slideUp('fast');
            $(this).toggleClass('open');
          }
        );
      });

app/views/pages/home.pt.html.haml
- if @user.errors.any?
  #error_explanation
    %h3 Infelizmente não foi possível completar a ação pois o formulario possui os seguintes erros
    %ul
      - @user.errors.full_messages.each do |message|
        %li= message

= simple_form_for @user, as: :user, url: homes_path(@user), method: :post  do |f|

  email
  = f.input_field :email
  nome
  = f.input_field :nome
  password
  = f.input_field :encrypted_password
  = f.button :submit

app/views/services/index.html.haml
%section.services
  .item
    %br.xs-30.sm-60
      .container.services-intro
        .row
          .col-md-6.masthead-img.animated.fadeInRightBig
            %form.form.masthead-form.well
              %h2.text-center.label-form O que você precisa ?
              %br
              .dropdown
                %a#dLabel.btn.btn-primar.btn-tipo{"data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  Tipo de Serviço
                  %span.caret
                %ul.dropdown-menu.multi-level{"aria-labelledby" => "dropdownMenu", :role => "menu"}
                  %li
                    %a{:href => "#"} Some action
                  %li
                    %a{:href => "#"} Some action    
          .col-md-6.destaques
            .well
              %h1.text-center Destaques
              - UserService.all.each do |f|
                .list-group
                  %a.list-group-item.diarista-destaque{:href => "#"}
                    .media.col-md-3
                      %figure.pull-left
                        %img.media-object.img-rounded.img-responsive{:alt => "placehold.it/350x250", :src => "http://placehold.it/350x250"}
                    .col-md-6
                      %h3 #{f.user.nome}
                      %h4.list-group-item-heading #{f.type_service.descricao}
                      %p.list-group-item-text
                        #{f.descricao}
                    .col-md-3.text-center
                      %h2
                        0
                        %small Seguidores
                      %button.btn.btn-default.btn-lg.btn-block{:type => "button"} Solicitar
                      = button_to 'Solicitar', seta_user_service_path(f),  :class => 'btn.btn-default.btn-lg'
                      .stars
                        %span.glyphicon.glyphicon-star
                        %span.glyphicon.glyphicon-star
                        %span.glyphicon.glyphicon-star
                        %span.glyphicon.glyphicon-star
                        %span.glyphicon.glyphicon-star-empty
                      %p
                        Nota 4.5
                        %small
      .col-md-6.masthead-img.animated.fadeInRightBig
        %form.form.masthead-form.well
          %h2.text-center.label-form Cadastre aqui seu serviço
          %br
            .form-group
              %textarea.area-diarista{:placeholder => "Descrição", :type => "text"}
              =simple_form_for @user_service , as: :user_service, url: us_path(@user_service), method: :post, :html =>{:class => 'form-group'}  do |f|
                = f.collection_select(:type_service_id, TypeService.all, :id, :descricao, prompt: true)
            %span.glyphicon.glyphicon-log-out.pull-right
            .form-group
              %br
              %button.btn.btn-secondary.btn-jumbo.btn-block.btn-cadastrar{:type => "submit"} Cadastrar
:javascript
  $(document).ready(function(){
    $('.dropdown').hover(
      function() {
        $('.dropdown-menu', this).not('.in.dropdown-menu').stop( true, true ).slideDown('fast');
        $(this).toggleClass('open');
      },
      function() {
        $('.dropdown-menu', this).not('.in.dropdown-menu').stop( true, true ).slideUp('fast');
        $(this).toggleClass('open');
      }
    );
  });

app/views/services/new.html.haml
=simple_form_for @service , as: :service, url: services_path(@service), method: :post, :html =>{:class => 'form-group'}  do |f|
  %h2 tudo

app/views/user_services/index.html.haml
- @user_services.each do |user_service|
  = user_service.descricao
  = user_service.type_service.descricao

app/views/user_services/new.html.haml
%section.cadastro-service
	.container
		.row
			%br.xs-80
				.account-wrapper
					.account-body
						.form.masthead-form
							%h2.text-center.label-form Cadastre aqui seu serviço
							%br
								.form-group
									=simple_form_for @user_service , as: :user_service, url: user_services_path(@user_service), method: :post, :html =>{:class => 'form-group'}  do |f|  
										= f.text_area :descricao, size: "50x12", :placeholder => 'Descrição' 
										= f.collection_select(:type_service_id, TypeService.all, :id, :descricao, prompt: true)
										%span.glyphicon.glyphicon-log-out.pull-right
										.form-group
											%br
											= f.button :submit, :html => 'btn btn-secondary btn-jumbo btn-block btn-cadastrar'

app/views/user_sessions/new.html.haml
- if @user_session.errors.has_key? :base
  %div
    = @user_session.errors[:base].join(',')



= form_for @user_session, as: :user_session, url: user_sessions_path(@user_session), method: :post  do |f|

  %fieldset
    %ol
      %li

        .input-group
          %label{:for => "email"} Email:
          %input.form-control{:type => "text", :email => "email", :class => "text"}


          .input-group
            %label{:for => "senha"} Senha:
            #{f.text_field :password,:placeholder => "Password" }
        = submit_tag 'Entrar'

app/views/users/show.html.haml
%h2
  Perfil #{current_user.email}
%ul
  %li
    Nome: #{@user.nome}
  %li
    Email: #{@user.email}

  = link_to 'cadastro' , new_user_service_path